// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package authdb

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, username string) (int64, error)
	GetUser(ctx context.Context, arg GetUserParams) error
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
